/**
 * @luna/ui-shared/core — framework-agnostic subset.
 *
 * No React (or any UI framework) imports. Safe to import from Solid,
 * Svelte, vanilla, server, or test code. Use this entry point from any
 * non-React UI surface (e.g. a Solid or vanilla-JS client).
 *
 * The default barrel (`@luna/ui-shared`) re-exports exactly this
 * surface — no extra framework-bound exports. UI components live with
 * their apps (e.g. the Moon's React frontend under
 * apps/ui-moon-tauri/frontend-react). Use this entry point from
 * non-React surfaces to keep that guarantee explicit.
 */
export {
  countLines,
  deriveTitle,
  formatBytes,
  formatMb,
  formatVal,
  newRequestId,
  relativeTime,
  truncate,
} from "./helpers.js"
export {
  ALLOWED_ATTACH_TYPES,
  MAX_ATTACH_BYTES,
  fileToAttachment,
  type PendingAttachment,
} from "./attachments.js"
export { downloadArtifact } from "./artifact-download.js"
export { closeOpenFences } from "./streaming.js"
export {
  SYSTEM_THREAD_TAG,
  initialState,
  reduce,
  filterEvents,
  type Action,
  type ChatLocalAction,
  type InFlightTurn,
  type PendingInputRequest,
  type ThreadView,
  type UIState,
} from "./reducer.js"
export {
  browserWebSocketTransport,
  type ConnectionStatus,
  type Transport,
  type TransportHandle,
} from "./transport.js"
export type {
  Artifact,
  ArtifactSource,
  ArtifactsExtractedFrame,
  AssistantDeltaFrame,
  AssistantDoneFrame,
  AssistantErrorFrame,
  ByeFrame,
  ChatAttachment,
  ChatErrorKind,
  ChatMessage,
  ChatToolUse,
  ClientFrame,
  DropFrame,
  EventFrame,
  HelloFrame,
  InterruptFrame,
  ListThreadsFrame,
  NewThreadFrame,
  ObsEvent,
  ObsEventBase,
  ObsEventKind,
  ObsEventLevel,
  PingFrame,
  PongFrame,
  ServerFrame,
  SessionSummary,
  SkillCatalogFrame,
  SkillCatalogItem,
  SkillStatusFrame,
  SkillToggleFrame,
  ConnectorCatalogFrame,
  ConnectorCatalogItem,
  ConnectorInstanceItem,
  ConnectorListFrame,
  ConnectorStatusFrame,
  ConnectorConnectFrame,
  ConnectorDisconnectFrame,
  ArtifactKind,
  ArtifactListFrame,
  ArtifactUpdateFrame,
  ArtifactPinFrame,
  ArtifactUnpinFrame,
  PinnedArtifactItem,
  SubscribeThreadFrame,
  ThreadCreatedFrame,
  ThreadListFrame,
  ThreadSnapshotFrame,
  UnsubscribeThreadFrame,
  UserAcceptedFrame,
  UserMessageFrame,
  WorkflowGalleryItem,
  WorkflowRunItem,
  WorkflowListFrame,
  WorkflowRunsFrame,
  WorkflowRunsRequestFrame,
  WorkflowRefreshFrame,
  JobInputRequestFrame,
  JobInputStatusFrame,
  JobInputResultFrame,
  VaultWireItem,
  VaultSyncWire,
  VaultStorageWire,
  VaultListFrame,
  VaultStatusFrame,
  VaultPutFrame,
  VaultDeleteFrame,
  VaultSyncConfigFrame,
  VaultImportFrame,
  SuggestedActionWire,
  SuggestedActionStatus,
  SuggestedActionType,
  SuggestedActionSetFrame,
  SuggestedActionUpdateFrame,
  SuggestedActionRespondFrame,
  ForkProposalWire,
  ForkProposalStatus,
  ForkProposalSetFrame,
  ForkProposalUpdateFrame,
  ForkProposalRespondFrame,
  ModelRoutingListFrame,
  ModelRoutingStatusFrame,
  ModelRoutingSaveFrame,
  ProviderSettingsItem,
  RoleBindingItem,
  ServerDescriptor,
  ServerDescriptorCapability,
  ServerKind,
  OperationName,
} from "./wire.js"
export { UI_WS_PROTOCOL_VERSION } from "./wire.js"
