/**
 * SessionHistoryService legacy tests — updated for Task 8 Effect-native API.
 *
 * These tests originally used a mock Promise-based API (the DuckDB stub).
 * They have been updated to use the new Effect-based API and the Memory layer.
 *
 * A richer set of real-implementation tests lives in:
 *   session-history-new.test.ts
 */

import { describe, expect, it } from "vitest"
import { Effect, Exit } from "effect"
import { Clock } from "../clock.js"
import { SessionHistoryService } from "./session-history.js"
import type { SessionRecordInput } from "./types.js"

// ── Helpers ───────────────────────────────────────────────────────────────────

const provideMemory = <A, E>(
  eff: Effect.Effect<A, E, SessionHistoryService | Clock>,
) =>
  eff.pipe(
    Effect.provide(SessionHistoryService.Memory),
    Effect.provide(Clock.Default),
  )

// ── Types & Contract ──────────────────────────────────────────────────────────

describe("SessionHistoryService", () => {
  describe("Types & Contract", () => {
    it("SessionRecordInput interface requires all mandatory fields", () => {
      const input: SessionRecordInput = {
        type: "user",
        entrypoint: "discord",
        sessionId: "sess-123",
        timestamp: new Date().toISOString(),
        textContent: "Hello",
      }
      expect(input.type).toBe("user")
      expect(input.textContent).toBe("Hello")
    })

    it("SessionRecordInput.type is a union of allowed values", () => {
      const types: SessionRecordInput["type"][] = ["user", "assistant", "system"]
      expect(types).toHaveLength(3)
    })

    it("Session IDs and UUIDs are distinct (uuid is generated by record)", async () => {
      const sessionId = "session-abc"
      const input: SessionRecordInput = {
        type: "assistant",
        entrypoint: "telegram",
        sessionId,
        timestamp: new Date().toISOString(),
        textContent: "Response",
        toolName: "Read",
      }

      const uuid = await Effect.runPromise(
        provideMemory(
          Effect.gen(function* () {
            const svc = yield* SessionHistoryService
            return yield* svc.record(input)
          }),
        ),
      )

      expect(typeof uuid).toBe("string")
      expect(uuid).not.toBe(sessionId)
    })
  })

  describe("BDD: Record a message and retrieve it", () => {
    it("Given an empty session history, When we record a message, Then record returns a uuid", async () => {
      const input: SessionRecordInput = {
        type: "user",
        entrypoint: "discord",
        sessionId: "sess-abc",
        timestamp: new Date().toISOString(),
        requestId: "req-1",
        textContent: "Test message",
      }

      const exit = await Effect.runPromiseExit(
        provideMemory(
          Effect.gen(function* () {
            const svc = yield* SessionHistoryService
            const uuid = yield* svc.record(input)
            expect(typeof uuid).toBe("string")
            expect(uuid.length).toBeGreaterThan(0)
          }),
        ),
      )

      expect(Exit.isSuccess(exit)).toBe(true)
    })

    it("Given recorded messages, When querying by sessionId, Then all messages are returned", async () => {
      const sessionId = "sess-multi"
      const t1 = new Date().toISOString()
      const t2 = new Date(Date.now() + 1000).toISOString()

      const exit = await Effect.runPromiseExit(
        provideMemory(
          Effect.gen(function* () {
            const svc = yield* SessionHistoryService
            yield* svc.record({ type: "user", entrypoint: "discord", sessionId, timestamp: t1, textContent: "First" })
            yield* svc.record({ type: "assistant", entrypoint: "discord", sessionId, timestamp: t2, textContent: "Response" })
            const results = yield* svc.query({ sessionId })
            expect(results).toHaveLength(2)
            expect(results.every((r) => r.sessionId === sessionId)).toBe(true)
          }),
        ),
      )

      expect(Exit.isSuccess(exit)).toBe(true)
    })

    it("Given a parent message, When recording a child message, Then parentUuid links them", async () => {
      const exit = await Effect.runPromiseExit(
        provideMemory(
          Effect.gen(function* () {
            const svc = yield* SessionHistoryService
            const parentId = yield* svc.record({
              type: "user",
              entrypoint: "discord",
              sessionId: "sess-thread",
              timestamp: new Date().toISOString(),
              textContent: "Parent question",
            })
            const childId = yield* svc.record({
              type: "assistant",
              entrypoint: "discord",
              sessionId: "sess-thread",
              parentUuid: parentId,
              timestamp: new Date(Date.now() + 100).toISOString(),
              textContent: "Child answer",
            })

            const rows = yield* svc.getSession("sess-thread")
            const child = rows.find((r) => r.uuid === childId)
            expect(child?.parentUuid).toBe(parentId)
          }),
        ),
      )

      expect(Exit.isSuccess(exit)).toBe(true)
    })
  })

  describe("Tool & Skill attribution", () => {
    it("Given a tool use, When recording with toolName, Then it can be queried by toolName", async () => {
      const exit = await Effect.runPromiseExit(
        provideMemory(
          Effect.gen(function* () {
            const svc = yield* SessionHistoryService
            yield* svc.record({
              type: "assistant",
              entrypoint: "discord",
              sessionId: "sess-tools",
              timestamp: new Date().toISOString(),
              toolUseId: "tool-use-123",
              textContent: "Using Read tool",
              toolName: "Read",
            })
            const results = yield* svc.query({ toolName: "Read" })
            expect(results).toHaveLength(1)
            expect(results[0]!.toolName).toBe("Read")
          }),
        ),
      )

      expect(Exit.isSuccess(exit)).toBe(true)
    })

    it("Given a skill invocation, When recording with skillName, Then it can be queried by skillName", async () => {
      const exit = await Effect.runPromiseExit(
        provideMemory(
          Effect.gen(function* () {
            const svc = yield* SessionHistoryService
            yield* svc.record({
              type: "assistant",
              entrypoint: "discord",
              sessionId: "sess-skills",
              timestamp: new Date().toISOString(),
              textContent: "Invoked skill",
              skillName: "advisor",
            })
            const results = yield* svc.query({ skillName: "advisor" })
            expect(results).toHaveLength(1)
            expect(results[0]!.skillName).toBe("advisor")
          }),
        ),
      )

      expect(Exit.isSuccess(exit)).toBe(true)
    })
  })

  describe("Querying & Retention", () => {
    it("getSession returns all messages in a session ordered by timestamp ASC", async () => {
      const sessionId = "sess-get"
      const t1 = new Date("2025-01-01T10:00:00.000Z").toISOString()
      const t2 = new Date("2025-01-01T11:00:00.000Z").toISOString()

      const exit = await Effect.runPromiseExit(
        provideMemory(
          Effect.gen(function* () {
            const svc = yield* SessionHistoryService
            // Insert in reverse order — getSession should sort ASC
            yield* svc.record({ type: "assistant", entrypoint: "discord", sessionId, timestamp: t2, textContent: "Second" })
            yield* svc.record({ type: "user", entrypoint: "discord", sessionId, timestamp: t1, textContent: "First" })
            const transcript = yield* svc.getSession(sessionId)
            expect(transcript).toHaveLength(2)
            expect(transcript[0]!.timestamp).toBe(t1)
            expect(transcript[1]!.timestamp).toBe(t2)
          }),
        ),
      )

      expect(Exit.isSuccess(exit)).toBe(true)
    })

    it("deleteOlderThan removes expired records and returns count", async () => {
      const old = new Date("2020-01-01T00:00:00.000Z").toISOString()
      const recent = new Date("2030-01-01T00:00:00.000Z").toISOString()
      const cutoffMs = new Date("2025-01-01T00:00:00.000Z").getTime()

      const exit = await Effect.runPromiseExit(
        provideMemory(
          Effect.gen(function* () {
            const svc = yield* SessionHistoryService
            yield* svc.record({ type: "user", entrypoint: "discord", sessionId: "sess-ret", timestamp: old, textContent: "old" })
            yield* svc.record({ type: "user", entrypoint: "discord", sessionId: "sess-ret", timestamp: recent, textContent: "new" })
            const deleted = yield* svc.deleteOlderThan(cutoffMs)
            expect(deleted).toBe(1)
            const remaining = yield* svc.getSession("sess-ret")
            expect(remaining).toHaveLength(1)
            expect(remaining[0]!.textContent).toBe("new")
          }),
        ),
      )

      expect(Exit.isSuccess(exit)).toBe(true)
    })
  })

  describe("Multi-entrypoint sessions", () => {
    it("Supports messages from different entrypoints (discord, telegram, cli)", async () => {
      const sessionId = "sess-multi-ep"
      const exit = await Effect.runPromiseExit(
        provideMemory(
          Effect.gen(function* () {
            const svc = yield* SessionHistoryService
            yield* svc.record({ type: "user", entrypoint: "discord", sessionId, timestamp: new Date().toISOString(), textContent: "From Discord" })
            yield* svc.record({ type: "user", entrypoint: "telegram", sessionId, timestamp: new Date().toISOString(), textContent: "From Telegram" })
            const results = yield* svc.query({ sessionId })
            expect(results).toHaveLength(2)
            const entrypoints = results.map((r) => r.entrypoint)
            expect(entrypoints).toContain("discord")
            expect(entrypoints).toContain("telegram")
          }),
        ),
      )

      expect(Exit.isSuccess(exit)).toBe(true)
    })
  })
})
