#!/usr/bin/env bun
/**
 * bundle-capabilities.ts
 *
 * Builds the zero-dependency @luna/capabilities surface into a single IIFE that
 * exposes all exports as window.LunaCapabilities. The output is committed as:
 *   apps/ui-moon-tauri/frontend/vendor/capabilities.js
 *
 * Run from repo root:
 *   bun run bundle:capabilities
 *
 * The Moon frontend <script src="vendor/capabilities.js"> loads this; after it
 * runs, window.LunaCapabilities.parseCommandLine, .filterCommands,
 * .completeCommand, .createCapabilityRegistry, .mergeCapabilities etc. are
 * available to the slash-command menu.
 *
 * GENERATED OUTPUT — do not hand-edit vendor/capabilities.js; regen with
 * `bun run bundle:capabilities` instead.
 */

import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, "..", "..", "..")
// The main barrel (src/index.ts) is zero-dep and browser-safe; the vitest-importing
// conformance suite lives behind the "./testing" subpath and is NOT reachable from here.
const entryPoint = resolve(repoRoot, "packages/capabilities/src/index.ts")
const outFile = resolve(__dirname, "..", "frontend/vendor/capabilities.js")

const HEADER = `// GENERATED by apps/ui-moon-tauri/scripts/bundle-capabilities.ts
// DO NOT HAND-EDIT — regen with: bun run bundle:capabilities
// Exposes window.LunaCapabilities with: parseCommandLine, filterCommands,
// completeCommand, createCapabilityRegistry, mergeCapabilities, decode* etc.
// Source: packages/capabilities/src/index.ts
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;

`

const FOOTER = `
  global.LunaCapabilities = module.exports;
})(typeof globalThis !== "undefined" ? globalThis : typeof window !== "undefined" ? window : this);
`

/**
 * Build the bundle and return the full output text.
 * Exported so tests can call it directly and compare to the committed file.
 */
export async function buildBundle(): Promise<string> {
  // Build as CJS so module.exports is available; we wrap it in an IIFE that
  // assigns the result to window.LunaCapabilities for vanilla <script> tags.
  const cjsResult = await Bun.build({
    entrypoints: [entryPoint],
    target: "browser",
    format: "cjs",
    minify: false,
    external: [],
  })

  if (!cjsResult.success) {
    const msgs = cjsResult.logs.map((l) => l.message).join("\n")
    throw new Error(`[bundle-capabilities] CJS build failed:\n${msgs}`)
  }

  const [cjsArtifact] = cjsResult.outputs
  const cjsBody = await cjsArtifact!.text()
  return HEADER + cjsBody + FOOTER
}

// When run as a script (not imported as a module), build and write the file.
// BUNDLE_OUT_FILE can override the destination (used by the staleness test to
// write to a temp path without clobbering the committed vendor file).
if (import.meta.main) {
  const dest = process.env.BUNDLE_OUT_FILE ?? outFile
  console.log("[bundle-capabilities] Building browser bundle…")
  console.log("  entry:", entryPoint)
  console.log("  out:  ", dest)

  const output = await buildBundle()

  // Sanity check: confirm key exports are present in the output
  const requiredExports = [
    "parseCommandLine",
    "filterCommands",
    "completeCommand",
    "createCapabilityRegistry",
    "mergeCapabilities",
  ]
  const missing = requiredExports.filter((name) => !output.includes(name))
  if (missing.length > 0) {
    console.error("[bundle-capabilities] ✗ Missing expected exports:", missing)
    process.exit(1)
  }
  console.log("[bundle-capabilities] ✓ All required exports found in bundle")

  // Confirm the firebreak held: vitest must never reach the browser bundle (the
  // conformance suite lives behind the ./testing subpath). Also guard any node:
  // builtin specifier so a future dependency can't silently leak into the IIFE.
  const NODE_SPECIFIER = /(^|[^A-Za-z0-9_$])node:[a-z][a-z/_-]*/
  const forbidden: { label: string; hit: () => boolean }[] = [
    { label: "vitest", hit: () => output.includes("vitest") },
    { label: "node: builtin specifier", hit: () => NODE_SPECIFIER.test(output) },
  ]
  const found = forbidden.filter((f) => f.hit()).map((f) => f.label)
  if (found.length > 0) {
    console.error("[bundle-capabilities] ✗ Bundle contains forbidden modules:", found)
    process.exit(1)
  }
  console.log("[bundle-capabilities] ✓ No vitest / no node: specifier in bundle")

  await Bun.write(dest, output)

  const sizeKb = (output.length / 1024).toFixed(1)
  console.log(`[bundle-capabilities] ✓ Written ${sizeKb} KB → ${dest}`)
}
