#!/usr/bin/env bun
/**
 * bundle-ui-transport.ts
 *
 * Builds the browser-safe @luna/ui-transport surface into a single IIFE that
 * exposes all exports as window.LunaTransport. The output is committed as:
 *   apps/ui-moon-tauri/frontend/vendor/ui-transport.js
 *
 * Run from repo root:
 *   bun run bundle:ui-transport
 *
 * The Moon frontend <script src="vendor/ui-transport.js"> loads this; after it
 * runs, window.LunaTransport.ConnectionManager, .selectAdapter, .LunaWsAdapter,
 * .HermesHttpSseAdapter etc. are available.
 *
 * GENERATED OUTPUT — do not hand-edit vendor/ui-transport.js; regen with
 * `bun run bundle:ui-transport` instead.
 */

import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, "..", "..", "..")
const entryPoint = resolve(repoRoot, "packages/ui-transport/src/browser.ts")
const outFile = resolve(__dirname, "..", "frontend/vendor/ui-transport.js")

const HEADER = `// GENERATED by apps/ui-moon-tauri/scripts/bundle-ui-transport.ts
// DO NOT HAND-EDIT — regen with: bun run bundle:ui-transport
// Exposes window.LunaTransport with: ConnectionManager, selectAdapter,
// LunaWsAdapter, HermesHttpSseAdapter, RouteHandle (type-only), etc.
// Source: packages/ui-transport/src/browser.ts
(function (global) {
  var module = { exports: {} };
  var exports = module.exports;

`

const FOOTER = `
  global.LunaTransport = module.exports;
})(typeof globalThis !== "undefined" ? globalThis : typeof window !== "undefined" ? window : this);
`

/**
 * Build the bundle and return the full output text.
 * Exported so tests can call it directly and compare to the committed file.
 */
export async function buildBundle(): Promise<string> {
  // Build as CJS so module.exports is available; we wrap it in an IIFE that
  // assigns the result to window.LunaTransport for vanilla <script> tags.
  const cjsResult = await Bun.build({
    entrypoints: [entryPoint],
    target: "browser",
    format: "cjs",
    minify: false,
    external: [],
  })

  if (!cjsResult.success) {
    const msgs = cjsResult.logs.map((l) => l.message).join("\n")
    throw new Error(`[bundle-ui-transport] CJS build failed:\n${msgs}`)
  }

  const [cjsArtifact] = cjsResult.outputs
  const cjsBody = await cjsArtifact!.text()
  return HEADER + cjsBody + FOOTER
}

// When run as a script (not imported as a module), build and write the file.
// BUNDLE_OUT_FILE can override the destination (used by the staleness test to
// write to a temp path without clobbering the committed vendor file).
if (import.meta.main) {
  const dest = process.env.BUNDLE_OUT_FILE ?? outFile
  console.log("[bundle-ui-transport] Building browser bundle…")
  console.log("  entry:", entryPoint)
  console.log("  out:  ", dest)

  const output = await buildBundle()

  await Bun.write(dest, output)

  const sizeKb = (output.length / 1024).toFixed(1)
  console.log(`[bundle-ui-transport] ✓ Written ${sizeKb} KB → ${dest}`)

  // Sanity check: confirm key exports are present in the output
  const requiredExports = [
    "ConnectionManager",
    "selectAdapter",
    "LunaWsAdapter",
    "HermesHttpSseAdapter",
  ]
  const missing = requiredExports.filter((name) => !output.includes(name))
  if (missing.length > 0) {
    console.error("[bundle-ui-transport] ✗ Missing expected exports:", missing)
    process.exit(1)
  }
  console.log("[bundle-ui-transport] ✓ All required exports found in bundle")

  // Confirm Node-only modules are absent. Guard against ANY `node:` builtin
  // specifier (not a hardcoded subset) so a future leak of node:child_process,
  // node:os, node:url, etc. — e.g. via the resolveTokenRef op:// path — cannot
  // slip past a clean-looking bundle. The leading-boundary class avoids matching
  // an identifier that merely ends in "node:" inside a larger word.
  const NODE_SPECIFIER = /(^|[^A-Za-z0-9_$])node:[a-z][a-z/_-]*/
  const forbidden: { label: string; hit: () => boolean }[] = [
    { label: "smol-toml", hit: () => output.includes("smol-toml") },
    { label: "node: builtin specifier", hit: () => NODE_SPECIFIER.test(output) },
  ]
  const found = forbidden.filter((f) => f.hit()).map((f) => f.label)
  if (found.length > 0) {
    console.error("[bundle-ui-transport] ✗ Bundle contains forbidden Node-only modules:", found)
    process.exit(1)
  }
  console.log("[bundle-ui-transport] ✓ No Node-only modules in bundle (no smol-toml / no node: specifier)")
}
